# Numpy

In [1]:
# import Numpy Library

import numpy as np

In [2]:
# creating simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
# Check dimension of array

arr.ndim

2

In [5]:
# Shape of array

arr.shape

(2, 4)

In [6]:
arr2 = np.array([1,2,3])
arr2

array([1, 2, 3])

In [7]:
arr2.ndim

1

In [8]:
arr2.shape

(3,)

In [9]:
# 3-dimension array

arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
arr3

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [10]:
arr3.ndim

2

In [11]:
arr3.shape

(3, 5)

In [12]:
# RAM Location of array

arr3.data

# Random Number Generator using Numpy

In [13]:
from numpy import random

x = random.randint(100)
x

28

In [14]:
x1 = random.randint(1000)
x2 = random.randint(1000)
x3 = random.randint(1000)
x4 = random.randint(1000)
x5 = random.randint(1000)

print('x1 = ',x1)
print('x2 = ',x2)
print('x3 = ',x3)
print('x4 = ',x4)
print('x5 = ',x5)

x1 =  972
x2 =  697
x3 =  1
x4 =  984
x5 =  601


In [15]:
for i in range(5):
    print(random.randint(1000))

898
643
318
517
333


In [16]:
# Generate random float number

z = random.rand()
z

0.9481464753496917

In [17]:
for i in range(10):
    print(random.rand())

0.15689816089717767
0.07248947872919875
0.01938462135350838
0.40331606658443364
0.9471695953131175
0.880299985003501
0.9356596696818934
0.3037498492879265
0.9965200067455193
0.06098907917816776


In [25]:
# Generate random array

x = random.randint(100,size=(5))
x

array([89, 87, 50, 69, 26])

In [26]:
x.shape

(5,)

In [27]:
x = random.randint(100,size=(5,8))
x

array([[96, 46, 65,  4, 97, 88, 77,  4],
       [74, 91, 82, 82, 62, 82,  0, 11],
       [69, 13,  2, 92, 34, 69, 86, 74],
       [57, 84, 63, 20, 75, 26, 87, 58],
       [ 2, 15, 29, 94, 24, 28,  6,  9]])

In [28]:
x.shape

(5, 8)

# Measure of central Tendency

In [32]:
array = random.randint(100,size=(5,3))
print(array)

[[54 10 52]
 [ 3 62 60]
 [64 14 59]
 [62 88  3]
 [12 97 20]]


In [33]:
# min function
print(np.amin(array))

# max function
print(np.amax(array))

3
97


In [35]:
# Finding Mean, Median, Standard Deviation and Variance in Numpy

a = np.array([5,6,7])
print('Mean of array a - ',np.mean(a))
print('Median of array a - ',np.median(a))
print('Standard Deviation of array a - ',np.std(a))
print('Variance of array a - ',np.var(a))

Mean of array a -  6.0
Median of array a -  6.0
Standard Deviation of array a -  0.816496580927726
Variance of array a -  0.6666666666666666


# Array broadcasting in numpy

In [46]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

In [47]:
a + b

array([3., 4., 5.])

In [48]:
a * b

array([2., 4., 6.])

In [49]:
a / b

array([0.5, 1. , 1.5])

In [50]:
a - b

array([-1.,  0.,  1.])